### ISSUE TITLE
Can't extract EzData.TRO

### ISSUE THREAD

**Issue by Leofravega** [Arrowgene/Arrowgene.Ez2Off#2]
Hi! 

I have some problem extracting EzData to the data folder required to run the server

This is my error code: 

Unhandled Exception: System.Exception: Can not read header, this is not a hdr file or the file is broken.

The paths are correct, and I'm using the "supported" client from the readme.

Thanks :)

**Comment by Leofravega** [comment]
Using the winx64 1.1 package from releases works for extracting. closing issue!

**Comment by sebastian-heinz** [comment]
You actually don't need to unpack to run the server, its just to inspect the data.

**Comment by Leofravega** [comment]
Yup, Now I understand it, now I have the server running and the game is detecting 2 server channels, but while creating a room it just crash.

How far are we to play this fully?

**Comment by sebastian-heinz** [comment]
To play you can use the offline version, that is in the mega.
It should also be possible to extend the offline version to play multiplayer. 
But its still very much work in progress everything, as i'd love to focus on the latest client that I cant get to run :/
